# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 182827c2290517534152ecfd4501e6c11c72231d1a822aa6d0468f23c4ca719ba98ddd16bdbb9c8ccfa04893bed3a6a38056dbf9d50de1c8e2978e42e4f8c747

test:
  secret_key_base: 5287445bf6acd3355567e90f69cef66be7e7a053c20cf8aa061d22d5cee20cc82def756d978fc4036b246ce5416f7c93b2f7f5ef637daa66fe10bdd99b1ad4c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
